#!/bin/bash

to_distro()
{
    local d="$1" v="$2"
    sed -re "1 s/\(([^)~]+)(~[^)]+)?\) ([^;]+)/\(\1${v:+~$v}\) $d/" -i debian/changelog
}

distros=`ubuntu-distro-info --supported`

if [[ "$1" == "all" ]]; then
    shift
    for distro in $distros; do
        to_distro $distro $distro
        "$0" "$@"
    done
    to_distro unstable ""
else
    dpkg-buildpackage --build=source --no-check-builddeps --no-pre-clean "$@"
fi
