#!/bin/bash

git-log-oneline() { git log --oneline --no-decorate "$@"; }

dch-add-from-stdin()
{
    while read sha msg; do
        local DEBFULLNAME=$(git show -s --format="%an" $sha)
        dch -a "$msg"
    done
    unset DEBFULLNAME
}

dch-bump-version()
{
    dch -Ui "Check version above and delete this line"
    dch -e
}

dch-release() { dch -rD unstable; }

dch-commit()
{
    local ver=$(dpkg-parsechangelog -S Version)
    git add debian/changelog
    git commit -m "Update changelog for $ver release"
}

git-debian-tag()
{
    local ver=$(dpkg-parsechangelog -S Version | sed "s/:/%/g")
    git tag debian/$ver
}

debian-release()
{
    local ver=$(dpkg-parsechangelog -S Version | sed "s/:/%/g")
    dch-bump-version
    git-log-oneline debian/${ver}..HEAD | dch-add-from-stdin
    dch-release
    dch-commit
    git-debian-tag
}

# detect if this script was sourced, and if so just export the functions
[[ "${0##*/}" == "bash" ]] || debian-release
